Repository HYO-Altair/ganttlet, pull requests merged in 2020-06, with the labels that each got.

#4 Firebase integration
  .github/workflows/node.js.yml
  package.json
  src/App.tsx
  src/components/Firebase/firebase.ts
  src/config/firebase/database_design_sample.json
  src/config/firebase/firebase_consts.tsx
Labels: enhancement, help wanted

#6 Login/signup
  .env
  package-lock.json
  package.json
  src/App.tsx
  src/components/Firebase/firebase.ts
  src/components/login/Login.tsx
  src/components/register/Register.tsx
  src/components/shared/ErrorDisplay.tsx
  src/config/firebase/database_design_sample.json
Labels: enhancement

#7 Home userprofile
  src/App.tsx
  src/components/dashboard/Dashboard.js
  src/components/dashboard/Table.js
  src/components/dashboard/Title.js
  src/components/dashboard/listItems.js
  src/components/footer/Footer.tsx
  src/components/home/FeatureCard.tsx
  src/components/home/FeatureSection.tsx
  src/components/home/HeadSection.tsx
  src/components/home/Home.tsx
  src/components/login/Login.tsx
  src/components/navigation/NavBar.tsx
  src/components/navigation/NavigationDrawer.tsx
  src/components/navigation/SideDrawer.tsx
  src/components/navigation/listItems.js
  src/components/profile/Profile.tsx
  src/components/profile/Title.tsx
  src/components/register/Register.tsx
  src/config/constants.ts
Labels: bug, enhancement
